class TSButton {
    static addTSButton() {
      // Проверяем, существует ли уже кнопка, чтобы избежать дублирования
      if ($('.ts-button').length) return;
  
      // Создаем элемент кнопки
      const tsButton = $(
        `<li class="text">
          <button type="button" class="ts-button" data-tooltip="TS Button" data-action="ts">
            <i class="fas fa-stopwatch"></i> TS
          </button>
        </li>`
      );
  
      // Паттерны автозамены
      const patterns = [
        // Кнопки Проверки
        { pattern: /Акробат[а-я]*_КС(\d+)/gi, replacement: '@Check[type:acrobatics|dc:$1]' },
        { pattern: /Аркан[а-я]*_КС(\d+)/gi, replacement: '@Check[type:arcana|dc:$1]' },
        { pattern: /Атлетик[а-я]*_КС(\d+)/gi, replacement: '@Check[type:athletics|dc:$1]' },
        { pattern: /Ремесл[а-я]*_КС(\d+)/gi, replacement: '@Check[type:crafting|dc:$1]' },
        { pattern: /Обман[а-я]*_КС(\d+)/gi, replacement: '@Check[type:deception|dc:$1]' },
        { pattern: /Дипломат[а-я]*_КС(\d+)/gi, replacement: '@Check[type:diplomacy|dc:$1]' },
        { pattern: /Запугиван[а-я]*_КС(\d+)/gi, replacement: '@Check[type:intimidation|dc:$1]' },
        { pattern: /Медицин[а-я]*_КС(\d+)/gi, replacement: '@Check[type:medicine|dc:$1]' },
        { pattern: /Природ[а-я]*_КС(\d+)/gi, replacement: '@Check[type:nature|dc:$1]' },
        { pattern: /Оккультизм[а-я]*_КС(\d+)/gi, replacement: '@Check[type:occultism|dc:$1]' },
        { pattern: /Выступлен[а-я]*_КС(\d+)/gi, replacement: '@Check[type:performance|dc:$1]' },
        { pattern: /Религ[а-я]*_КС(\d+)/gi, replacement: '@Check[type:religion|dc:$1]' },
        { pattern: /Обществ[а-я]*_КС(\d+)/gi, replacement: '@Check[type:society|dc:$1]' },
        { pattern: /Скрытн[а-я]*_КС(\d+)/gi, replacement: '@Check[type:stealth|dc:$1]' },
        { pattern: /Выживан[а-я]*_КС(\d+)/gi, replacement: '@Check[type:survival|dc:$1]' },
        { pattern: /Воровств[а-я]*_КС(\d+)/gi, replacement: '@Check[type:thievery|dc:$1]' },
        { pattern: /Восприят[а-я]*_КС(\d+)/gi, replacement: '@Check[type:perception|dc:$1]' },
        { pattern: /Чист[а-я]*_КС(\d+)/gi, replacement: '@Check[type:flat|dc:$1]' },

        { pattern: /Знан[а-я]*: Тассилон[а-я]*_КС(\d+)/gi, replacement: '@Check[type:thassilon-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Академич[а-я]*_КС(\d+)/gi, replacement: '@Check[type:academia-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Бухгалтер[а-я]*_КС(\d+)/gi, replacement: '@Check[type:accounting-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Архитектур[а-я]*_КС(\d+)/gi, replacement: '@Check[type:architecture-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Искусств[а-я]*_КС(\d+)/gi, replacement: '@Check[type:art-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Цирков[а-я]*_КС(\d+)/gi, replacement: '@Check[type:circus-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Инженер[а-я]*_КС(\d+)/gi, replacement: '@Check[type:engineering-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Фермер[а-я]*_КС(\d+)/gi, replacement: '@Check[type:farming-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Рыба[а-я]*_КС(\d+)/gi, replacement: '@Check[type:fishing-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Предсказан[а-я]*_КС(\d+)/gi, replacement: '@Check[type:fortune-telling-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Игр[а-я]*_КС(\d+)/gi, replacement: '@Check[type:games-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Генеалог[а-я]*_КС(\d+)/gi, replacement: '@Check[type:genealogy-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Гладиатор[а-я]*_КС(\d+)/gi, replacement: '@Check[type:gladiatorial-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Гильд[а-я]*_КС(\d+)/gi, replacement: '@Check[type:guild-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Геральд[а-я]*_КС(\d+)/gi, replacement: '@Check[type:heraldry-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Травнич[а-я]*_КС(\d+)/gi, replacement: '@Check[type:herbalism-lore|dc:$1]' },        
        { pattern: /Знан[а-я]*: Охот[а-я]*_КС(\d+)/gi, replacement: '@Check[type:hunting-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Труд[а-я]*_КС(\d+)/gi, replacement: '@Check[type:labor-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Юридич[а-я]*_КС(\d+)/gi, replacement: '@Check[type:legal-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Библиотеч[а-я]*_КС(\d+)/gi, replacement: '@Check[type:library-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Коммерчес[а-я]*_КС(\d+)/gi, replacement: '@Check[type:mercantile-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Акушер[а-я]*_КС(\d+)/gi, replacement: '@Check[type:midwifery-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Мельнич[а-я]*_КС(\d+)/gi, replacement: '@Check[type:milling-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Шахтер[а-я]*_КС(\d+)/gi, replacement: '@Check[type:mining-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Монах[а-я]*_КС(\d+)/gi, replacement: '@Check[type:monk-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Мореход[а-я]*_КС(\d+)/gi, replacement: '@Check[type:sailing-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Путник[а-я]*_КС(\d+)/gi, replacement: '@Check[type:traveller-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Торгов[а-я]*_КС(\d+)/gi, replacement: '@Check[type:trading-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Развед[а-я]*_КС(\d+)/gi, replacement: '@Check[type:scouting-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Письмен[а-я]*_КС(\d+)/gi, replacement: '@Check[type:scribing-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Кон[а-я]*_КС(\d+)/gi, replacement: '@Check[type:stabling-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Кож[а-я]*_КС(\d+)/gi, replacement: '@Check[type:tanning-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Театр[а-я]*_КС(\d+)/gi, replacement: '@Check[type:theater-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Прест[а-я]* Мир[а-я]*_КС(\d+)/gi, replacement: '@Check[type:underworld-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Воен[а-я]* Дел[а-я]*_КС(\d+)/gi, replacement: '@Check[type:warfare-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Динозавр[а-я]*_КС(\d+)/gi, replacement: '@Check[type:dinosaur-lore|dc:$1]' },
        { pattern: /Знан[а-я]*: Обществ[а-я]*_Искател[а-я]*_КС(\d+)/gi, replacement: '@Check[type:pathfinder-society-lore|dc:$1]' },
        { pattern: /КС_(\d+)/gi, replacement: 'КС$1' },


        // Паттерны для обычных спасбросков
        { pattern: /(?<!Пр\.)Спас\.РФЛ_КС(\d+)/gi, replacement: '@Check[type:reflex|dc:$1]' },
        { pattern: /(?<!Пр\.)Спас\.СТК_КС(\d+)/gi, replacement: '@Check[type:fortitude|dc:$1]' },
        { pattern: /(?<!Пр\.)Спас\.Воля_КС(\d+)/gi, replacement: '@Check[type:will|dc:$1]' },
        // Паттерны для базовых спасбросков (Пр.Спас)
        { pattern: /Пр\.Спас\.РФЛ_КС(\d+)/gi, replacement: '@Check[type:reflex|dc:$1|basic:true]' },
        { pattern: /Пр\.Спас\.СТК_КС(\d+)/gi, replacement: '@Check[type:fortitude|dc:$1|basic:true]' },
        { pattern: /Пр\.Спас\.Воля_КС(\d+)/gi, replacement: '@Check[type:will|dc:$1|basic:true]' },
        // Область
        { pattern: /Эманац[а-я]*_(\d+)/gi, replacement: '@Template[type:emanation|distance:$1]' },
        { pattern: /Конус[а-я]*_(\d+)/gi, replacement: '@Template[type:cone|distance:$1]' },
        { pattern: /Взрыв[а-я]*_(\d+)/gi, replacement: '@Template[type:burst|distance:$1]' },
        { pattern: /Линия[а-я]*_(\d+)/gi, replacement: '@Template[type:line|distance:$1]' },


        // Разное
        { pattern: /\@Compendium\[pf2e\./gi, replacement: '@UUID[Compendium.pf2e.' },
        { pattern: /дескриптор/gi, replacement: 'Признак' },
        { pattern: / \.Успех/gi, replacement: ' Успех' },
        { pattern: / \.Провал/gi, replacement: ' Провал' },
        { pattern: /Восприяти[а-я]*_\+(\d+)/gi, replacement: '@Check[type:perception|traits:initiative]{Восприятие +$1}' },
        { pattern: /Скрытност[а-я]*_\+(\d+)/gi, replacement: '@Check[type:stealth|traits:initiative]{Скрытность +$1}' },

        // Кнопки Урона
        // Огонь
        { pattern: /(\d+d\d+|\d+) урон[а-я]* огн[а-я]*/gi, replacement: '@Damage[($1)[fire]]' },
        { pattern: /(\d+d\d+|\d+) огненн[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[fire]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* огн[а-я]*/gi, replacement: '@Damage[($1)[persistent,fire]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* огненн[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,fire]]' },

        // Кислота
        { pattern: /(\d+d\d+|\d+) урон[а-я]* кислот[а-я]*/gi, replacement: '@Damage[($1)[acid]]' },
        { pattern: /(\d+d\d+|\d+) кислот[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[acid]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* кислот[а-я]*/gi, replacement: '@Damage[($1)[persistent,acid]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* кислот[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,acid]]' },

        // Яд
        { pattern: /(\d+d\d+|\d+) урон[а-я]* яд[а-я]*/gi, replacement: '@Damage[($1)[poison]]' },
        { pattern: /(\d+d\d+|\d+) ядовит[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[poison]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* яд[а-я]*/gi, replacement: '@Damage[($1)[persistent,poison]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* ядовит[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,poison]]' },

        // Холод
        { pattern: /(\d+d\d+|\d+) урон[а-я]* холод[а-я]*/gi, replacement: '@Damage[($1)[cold]]' },
        { pattern: /(\d+d\d+|\d+) холод[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[cold]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* холод[а-я]*/gi, replacement: '@Damage[($1)[persistent,cold]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* холод[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,cold]]' },

        // Электричество
        { pattern: /(\d+d\d+|\d+) урон[а-я]* электрич[а-я]*/gi, replacement: '@Damage[($1)[electricity]]' },
        { pattern: /(\d+d\d+|\d+) электрич[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[electricity]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* электрич[а-я]*/gi, replacement: '@Damage[($1)[persistent,electricity]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* электрич[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,electricity]]' },

        // Дробящий
        { pattern: /(\d+d\d+|\d+) урон[а-я]* дробящ[а-я]*/gi, replacement: '@Damage[($1)[bludgeoning]]' },
        { pattern: /(\d+d\d+|\d+) дробящ[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[bludgeoning]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* дробящ[а-я]*/gi, replacement: '@Damage[($1)[persistent,bludgeoning]]' },
        { pattern: /(\d+d\d+|\d+) спродолжительн[а-я]* дробящ[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,bludgeoning]]' },

        // Колющий
        { pattern: /(\d+d\d+|\d+) урон[а-я]* колющ[а-я]*/gi, replacement: '@Damage[($1)[piercing]]' },
        { pattern: /(\d+d\d+|\d+) колющ[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[piercing]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* колющ[а-я]*/gi, replacement: '@Damage[($1)[persistent,piercing]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* колющ[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,piercing]]' },

        // Рубящий
        { pattern: /(\d+d\d+|\d+) урон[а-я]* рубящ[а-я]*/gi, replacement: '@Damage[($1)[slashing]]' },
        { pattern: /(\d+d\d+|\d+) рубящ[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[slashing]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* рубящ[а-я]*/gi, replacement: '@Damage[($1)[persistent,slashing]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* рубящ[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,slashing]]' },

        // Кровотечение
        { pattern: /(\d+d\d+|\d+) кровотеч[а-я]*/gi, replacement: '@Damage[($1)[bleed]]' },
        { pattern: /(\d+d\d+|\d+) урон[а-я]* кровотеч[а-я]*/gi, replacement: '@Damage[($1)[bleed]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* кровотеч[а-я]*/gi, replacement: '@Damage[($1)[persistent,bleed]]' },

        // Ментальный
        { pattern: /(\d+d\d+|\d+) урон[а-я]* ментал[а-я]*/gi, replacement: '@Damage[($1)[mental]]' },
        { pattern: /(\d+d\d+|\d+) ментал[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[mental]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* ментал[а-я]*/gi, replacement: '@Damage[($1)[persistent,mental]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* ментал[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,mental]]' },

        // Силой
        { pattern: /(\d+d\d+|\d+) урон[а-я]* сил[а-я]*/gi, replacement: '@Damage[($1)[force]]' },
        { pattern: /(\d+d\d+|\d+) сил[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[force]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* сил[а-я]*/gi, replacement: '@Damage[($1)[persistent,force]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* сил[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,force]]' },

        // Звук
        { pattern: /(\d+d\d+|\d+) урон[а-я]* звук[а-я]*/gi, replacement: '@Damage[($1)[sonic]]' },
        { pattern: /(\d+d\d+|\d+) звук[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[sonic]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* урон[а-я]* звук[а-я]*/gi, replacement: '@Damage[($1)[persistent,sonic]]' },
        { pattern: /(\d+d\d+|\d+) продолжительн[а-я]* звук[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[persistent,sonic]]' },
        
        // Точный
        { pattern: /(\d+d\d+|\d+) урон[а-я]* точн[а-я]*/gi, replacement: '@Damage[($1)[precision]]' },
        { pattern: /(\d+d\d+|\d+) точн[а-я]* урон[а-я]*/gi, replacement: '@Damage[($1)[precision]]' },

        // Признаки
        { pattern: /`Аберрац[а-я]*`/gi, replacement: '@Trait[Aberration]{Аберрация}' },
        { pattern: /`Кислот[а-я]*`/gi, replacement: '@Trait[Acid]{Кислота}' },
        { pattern: /`Примесь 0`/gi, replacement: '@Trait[Additive0]{Примесь 0}' },
        { pattern: /`Примесь 1`/gi, replacement: '@Trait[Additive1]{Примесь 1}' },
        { pattern: /`Примесь 2`/gi, replacement: '@Trait[Additive2]{Примесь 2}' },
        { pattern: /`Примесь 3`/gi, replacement: '@Trait[Additive3]{Примесь 3}' },
        { pattern: /`Приспособленн[а-я]*`/gi, replacement: '@Trait[Adjusted]{Приспособленный}' },
        { pattern: /`Приспособление`/gi, replacement: '@Trait[Adjustment]{Приспособление}' },
        { pattern: /`Эон`/gi, replacement: '@Trait[Aeon]{Эон}' },
        { pattern: /`Ас[а-я]*`/gi, replacement: '@Trait[Aesir]{Асы}' },
        { pattern: /`Последств[а-я]*`/gi, replacement: '@Trait[Aftermath]{Последствие}' },
        { pattern: /`Агатион[а-я]*`/gi, replacement: '@Trait[Agathion]{Агатион}' },
        { pattern: /`Быстр[а-я]*`/gi, replacement: '@Trait[Agile]{Быстрое}' },
        { pattern: /`Воздух[а-я]*`/gi, replacement: '@Trait[Air]{Воздух}' },
        { pattern: /`Аюварин[а-я]*`/gi, replacement: '@Trait[Aiuvarin]{Аюварин}' },
        { pattern: /`Алхимическ[а-я]*`/gi, replacement: '@Trait[Alchemical]{Алхимический}' },
        { pattern: /`Алхимик`/gi, replacement: '@Trait[Alchemist]{Алхимик}' },
        { pattern: /`Расширение`/gi, replacement: '@Trait[Amp]{Расширение}' },
        { pattern: /`Земноводн[а-я]*`/gi, replacement: '@Trait[Amphibious]{Земноводный}' },
        { pattern: /`Анади`/gi, replacement: '@Trait[Anadi]{Анади}' },
        { pattern: /`Андроид`/gi, replacement: '@Trait[Android]{Андроид}' },
        { pattern: /`Ангел`/gi, replacement: '@Trait[Angel]{Ангел}' },
        { pattern: /`Животн[а-я]*`/gi, replacement: '@Trait[Animal]{Животное}' },
        { pattern: /`Анугобу`/gi, replacement: '@Trait[Anugobu]{Анугобу}' },
        { pattern: /`Наивысш[а-я]*`/gi, replacement: '@Trait[Apex]{Наивысший}' },
        { pattern: /`Афорит`/gi, replacement: '@Trait[Aphorite]{Афорит}' },
        { pattern: /`Обтекаем[а-я]*`/gi, replacement: '@Trait[Aquadynamic]{Обтекаемый}' },
        { pattern: /`Водн[а-я]*`/gi, replacement: '@Trait[Aquatic]{Водный}' },
        { pattern: /`Аркана`/gi, replacement: '@Trait[Arcane]{Аркана}' },
        { pattern: /`Архетип[а-я]*`/gi, replacement: '@Trait[Archetype]{Архетип}' },
        { pattern: /`Архон`/gi, replacement: '@Trait[Archon]{Архон}' },
        { pattern: /`Арданд`/gi, replacement: '@Trait[Ardande]{Арданд}' },
        { pattern: /`Урон по области`/gi, replacement: '@Trait[AreaDamage]{Урон по области}' },
        { pattern: /`Артефакт`/gi, replacement: '@Trait[Artifact]{Артефакт}' },
        { pattern: /`Астральн[а-я]*`/gi, replacement: '@Trait[Astral]{Астральный}' },
        { pattern: /`Асура`/gi, replacement: '@Trait[Asura]{Асура}' },
        { pattern: /`Атамару`/gi, replacement: '@Trait[Athamaru]{Атамару}' },
        { pattern: /`Прикрепляем[а-я]*`/gi, replacement: '@Trait[Attached]{Прикрепляемый}' },
        { pattern: /`Атак[а-я]*`/gi, replacement: '@Trait[Attack]{Атака}' },
        { pattern: /`Слухов[а-я]*`/gi, replacement: '@Trait[Auditory]{Слуховой}' },
        { pattern: /`Аура`/gi, replacement: '@Trait[Aura]{Аура}' },
        { pattern: /`Автоматон`/gi, replacement: '@Trait[Automaton]{Автоматон}' },
        { pattern: /`Пробуждённое животн[а-я]*`/gi, replacement: '@Trait[AwakenedAnimal]{Пробуждённое животное}' },
        { pattern: /`Азаркет`/gi, replacement: '@Trait[Azarketi]{Азаркет}' },
        { pattern: /`Азата`/gi, replacement: '@Trait[Azata]{Азата}' },
        { pattern: /`Предательск[а-я]*`/gi, replacement: '@Trait[Backstabber]{Предательское}' },
        { pattern: /`Обратный замах`/gi, replacement: '@Trait[Backswing]{Обратный замах}' },
        { pattern: /`Варвар`/gi, replacement: '@Trait[Barbarian]{Варвар}' },
        { pattern: /`Бард`/gi, replacement: '@Trait[Bard]{Бард}' },
        { pattern: /`Barding`/gi, replacement: '@Trait[Barding]{Barding}' },
        { pattern: /`Чудовищ[а-я]*`/gi, replacement: '@Trait[Beast]{Чудовище}' },
        { pattern: /`Зверолюд[а-я]*`/gi, replacement: '@Trait[Beastkin]{Зверолюд}' },
        { pattern: /`Кровотечен[а-я]*`/gi, replacement: '@Trait[Bleed]{Кровотечение}' },
        { pattern: /`Дробящ[а-я]*`/gi, replacement: '@Trait[Bludgeoning]{Дробящий}' },
        { pattern: /`Боггард`/gi, replacement: '@Trait[Boggard]{Боггард}' },
        { pattern: /`Бомба`/gi, replacement: '@Trait[Bomb]{Бомба}' },
        { pattern: /`Узы`/gi, replacement: '@Trait[Bonded]{Узы}' },
        { pattern: /`Дыхание в бутылке`/gi, replacement: '@Trait[BottledBreath]{Дыхание в бутылке}' },
        { pattern: /`Brace`/gi, replacement: '@Trait[Brace]{Brace}' },
        { pattern: /`Брутальн[а-я]*`/gi, replacement: '@Trait[Brutal]{Брутальное}' },
        { pattern: /`Багбер`/gi, replacement: '@Trait[Bugbear]{Багбер}' },
        { pattern: /`Защитн[а-я]*`/gi, replacement: '@Trait[Bulwark]{Защитный}' },
        { pattern: /`Калигни`/gi, replacement: '@Trait[Caligni]{Калигни}' },
        { pattern: /`Чары`/gi, replacement: '@Trait[Cantrip]{Чары}' },
        { pattern: /`Вместимость`/gi, replacement: '@Trait[Capacity]{Вместимость}' },
        { pattern: /`Вместимость 2`/gi, replacement: '@Trait[Capacity2]{Вместимость 2}' },
        { pattern: /`Вместимость 3`/gi, replacement: '@Trait[Capacity3]{Вместимость 3}' },
        { pattern: /`Вместимость 4`/gi, replacement: '@Trait[Capacity4]{Вместимость 4}' },
        { pattern: /`Вместимость 5`/gi, replacement: '@Trait[Capacity5]{Вместимость 5}' },
        { pattern: /`Носим[а-я]*`/gi, replacement: '@Trait[Carried]{Носимый}' },
        { pattern: /`Катализатор`/gi, replacement: '@Trait[Catalyst]{Катализатор}' },
        { pattern: /`Коточеловек`/gi, replacement: '@Trait[Catfolk]{Коточеловек}' },
        { pattern: /`Небожител[а-я]*`/gi, replacement: '@Trait[Celestial]{Небожитель}' },
        { pattern: /`Кентавр`/gi, replacement: '@Trait[Centaur]{Кентавр}' },
        { pattern: /`Certain Kill`/gi, replacement: '@Trait[CertainKill]{Certain Kill}' },
        { pattern: /`Чемпион`/gi, replacement: '@Trait[Champion]{Чемпион}' },
        { pattern: /`Подменыш`/gi, replacement: '@Trait[Changeling]{Подменыш}' },
        { pattern: /`Чарау-ка`/gi, replacement: '@Trait[CharauKa]{Чарау-ка}' },
        { pattern: /`Цирк`/gi, replacement: '@Trait[Circus]{Цирк}' },
        { pattern: /`Жрец`/gi, replacement: '@Trait[Cleric]{Жрец}' },
        { pattern: /`Карабканье`/gi, replacement: '@Trait[Climbing]{Карабканье}' },
        { pattern: /`Заводной`/gi, replacement: '@Trait[Clockwork]{Заводной}' },
        { pattern: /`Сварганенн[а-я]*`/gi, replacement: '@Trait[Cobbled]{Сварганенное}' },
        { pattern: /`Кода`/gi, replacement: '@Trait[Coda]{Кода}' },
        { pattern: /`Холод`/gi, replacement: '@Trait[Cold]{Холод}' },
        { pattern: /`Холодное железо`/gi, replacement: '@Trait[Coldiron]{Холодное железо}' },
        { pattern: /`Комбинированн[а-я]*`/gi, replacement: '@Trait[Combination]{Комбинированное}' },
        { pattern: /`Удобн[а-я]*`/gi, replacement: '@Trait[Comfort]{Удобный}' },
        { pattern: /`Обычн[а-я]*`/gi, replacement: '@Trait[Common]{Обычный}' },
        { pattern: /`Компаньон[а-я]*`/gi, replacement: '@Trait[Companion]{Компаньон}' },
        { pattern: /`Комплексн[а-я]*`/gi, replacement: '@Trait[Complex]{Комплексная}' },
        { pattern: /`Составн[а-я]*`/gi, replacement: '@Trait[Composite]{Составной}' },
        { pattern: /`Композиц[а-я]*`/gi, replacement: '@Trait[Composition]{Композиция}' },
        { pattern: /`Скрываем[а-я]*`/gi, replacement: '@Trait[Concealable]{Скрываемое}' },
        { pattern: /`Концентрац[а-я]*`/gi, replacement: '@Trait[Concentrate]{Концентрация}' },
        { pattern: /`Сотрясающ[а-я]*`/gi, replacement: '@Trait[Concussive]{Сотрясающее}' },
        { pattern: /`Замешательство`/gi, replacement: '@Trait[Confusion]{Замешательство}' },
        { pattern: /`Конрас`/gi, replacement: '@Trait[Conrasu]{Конрас}' },
        { pattern: /`Освящен[а-я]*`/gi, replacement: '@Trait[Consecration]{Освящение}' },
        { pattern: /`Конструкт[а-я]*`/gi, replacement: '@Trait[Construct]{Конструкт}' },
        { pattern: /`Расходуем[а-я]*`/gi, replacement: '@Trait[Consumable]{Расходуемый}' },
        { pattern: /`Контакт`/gi, replacement: '@Trait[Contact]{Контакт}' },
        { pattern: /`Сопряженность`/gi, replacement: '@Trait[Contingency]{Сопряженность}' },
        { pattern: /`Контракт`/gi, replacement: '@Trait[Contract]{Контракт}' },
        { pattern: /`Коатль`/gi, replacement: '@Trait[Couatl]{Коатль}' },
        { pattern: /`Критическое слияние`/gi, replacement: '@Trait[CriticalFusion]{Критическое слияние}' },
        { pattern: /`Проклят[а-я]*`/gi, replacement: '@Trait[Curse]{Проклятие}' },
        { pattern: /`Оковы проклятия`/gi, replacement: '@Trait[Cursebound]{Оковы проклятия}' },
        { pattern: /`Проклят[а-я]*`/gi, replacement: '@Trait[Cursed]{Проклятый}' },
        { pattern: /`Дэймон`/gi, replacement: '@Trait[Daemon]{Дэймон}' },
        { pattern: /`Тьма`/gi, replacement: '@Trait[Darkness]{Тьма}' },
        { pattern: /`Дарвакка`/gi, replacement: '@Trait[Darvakka]{Дарвакка}' },
        { pattern: /`Смертельн[а-я]*`/gi, replacement: '@Trait[Deadly]{Смертельное}' },
        { pattern: /`Смертельное 2d10`/gi, replacement: '@Trait[Deadly2D10]{Смертельное 2d10}' },
        { pattern: /`Смертельное 2d12`/gi, replacement: '@Trait[Deadly2D12]{Смертельное 2d12}' },
        { pattern: /`Смертельное 2d8`/gi, replacement: '@Trait[Deadly2D8]{Смертельное 2d8}' },
        { pattern: /`Смертельное 3d10`/gi, replacement: '@Trait[Deadly3D10]{Смертельное 3d10}' },
        { pattern: /`Смертельное 3d12`/gi, replacement: '@Trait[Deadly3D12]{Смертельное 3d12}' },
        { pattern: /`Смертельное 3d8`/gi, replacement: '@Trait[Deadly3D8]{Смертельное 3d8}' },
        { pattern: /`Смертельное 4d10`/gi, replacement: '@Trait[Deadly4D10]{Смертельное 4d10}' },
        { pattern: /`Смертельное 4d12`/gi, replacement: '@Trait[Deadly4D12]{Смертельное 4d12}' },
        { pattern: /`Смертельное 4d8`/gi, replacement: '@Trait[Deadly4D8]{Смертельное 4d8}' },
        { pattern: /`Смертельное d10`/gi, replacement: '@Trait[DeadlyD10]{Смертельное d10}' },
        { pattern: /`Смертельное d12`/gi, replacement: '@Trait[DeadlyD12]{Смертельное d12}' },
        { pattern: /`Смертельное d4`/gi, replacement: '@Trait[DeadlyD4]{Смертельное d4}' },
        { pattern: /`Смертельное d6`/gi, replacement: '@Trait[DeadlyD6]{Смертельное d6}' },
        { pattern: /`Смертельное d8`/gi, replacement: '@Trait[DeadlyD8]{Смертельное d8}' },
        { pattern: /`Смерть`/gi, replacement: '@Trait[Death]{Смерть}' },
        { pattern: /`Посвящен[а-я]*`/gi, replacement: '@Trait[Dedication]{Посвящение}' },
        { pattern: /`Демон[а-я]*`/gi, replacement: '@Trait[Demon]{Демон}' },
        { pattern: /`Деро`/gi, replacement: '@Trait[Dero]{Деро}' },
        { pattern: /`Обнаружен[а-я]*`/gi, replacement: '@Trait[Detection]{Обнаружение}' },
        { pattern: /`Девиантн[а-я]*`/gi, replacement: '@Trait[Deviant]{Девиантный}' },
        { pattern: /`Дьявол[а-я]*`/gi, replacement: '@Trait[Devil]{Дьявол}' },
        { pattern: /`Дампир`/gi, replacement: '@Trait[Dhampir]{Дампир}' },
        { pattern: /`Динозавр[а-я]*`/gi, replacement: '@Trait[Dinosaur]{Динозавр}' },
        { pattern: /`Разоружени[а-я]*`/gi, replacement: '@Trait[Disarm]{Разоружение}' },
        { pattern: /`Болезн[а-я]*`/gi, replacement: '@Trait[Disease]{Болезнь}' },
        { pattern: /`Див`/gi, replacement: '@Trait[Div]{Див}' },
        { pattern: /`Сакральн[а-я]*`/gi, replacement: '@Trait[Divine]{Сакральный}' },
        { pattern: /`Двуствольн[а-я]*`/gi, replacement: '@Trait[DoubleBarrel]{Двуствольное}' },
        { pattern: /`Отдых`/gi, replacement: '@Trait[Downtime]{Отдых}' },
        { pattern: /`Дракон[а-я]*`/gi, replacement: '@Trait[Dragon]{Дракон}' },
        { pattern: /`Сновидение`/gi, replacement: '@Trait[Dream]{Сновидение}' },
        { pattern: /`Дромаар`/gi, replacement: '@Trait[Dromaar]{Дромаар}' },
        { pattern: /`Дроу`/gi, replacement: '@Trait[Drow]{Дроу}' },
        { pattern: /`Наркотик`/gi, replacement: '@Trait[Drug]{Наркотик}' },
        { pattern: /`Друид`/gi, replacement: '@Trait[Druid]{Друид}' },
        { pattern: /`Хрингар`/gi, replacement: '@Trait[Duergar]{Хрингар}' },
        { pattern: /`Сумеречн[а-я]*`/gi, replacement: '@Trait[Duskwalker]{Сумеречный}' },
        { pattern: /`Дварф[а-я]*`/gi, replacement: '@Trait[Dwarf]{Дварф}' },
        { pattern: /`Земля`/gi, replacement: '@Trait[Earth]{Земля}' },
        { pattern: /`Эйдолон`/gi, replacement: '@Trait[Eidolon]{Эйдолон}' },
        { pattern: /`Электричеств[а-я]*`/gi, replacement: '@Trait[Electricity]{Электричество}' },
        { pattern: /`Элементал[а-я]*`/gi, replacement: '@Trait[Elemental]{Элементаль}' },
        { pattern: /`Эльф`/gi, replacement: '@Trait[Elf]{Эльф}' },
        { pattern: /`Эликсир`/gi, replacement: '@Trait[Elixir]{Эликсир}' },
        { pattern: /`Эмоци[а-я]*`/gi, replacement: '@Trait[Emotion]{Эмоция}' },
        { pattern: /`Энерги[а-я]*`/gi, replacement: '@Trait[Energy]{Энергия}' },
        { pattern: /`Окружени[а-я]*`/gi, replacement: '@Trait[Environmental]{Окружение}' },
        { pattern: /`Эзотерика`/gi, replacement: '@Trait[Esoterica]{Эзотерика}' },
        { pattern: /`Эфириал`/gi, replacement: '@Trait[Ethereal]{Эфириал}' },
        { pattern: /`Эволюция`/gi, replacement: '@Trait[Evolution]{Эволюция}' },
        { pattern: /`Expandable`/gi, replacement: '@Trait[Expandable]{Expandable}' },
        { pattern: /`Экспериментальн[а-я]*`/gi, replacement: '@Trait[Experiment]{Экспериментальный}' },
        { pattern: /`Исследовани[а-я]*`/gi, replacement: '@Trait[Exploration]{Исследование}' },
        { pattern: /`Межпространственн[а-я]*`/gi, replacement: '@Trait[Extradimensional]{Межпространственный}' },
        { pattern: /`Фатальн[а-я]*`/gi, replacement: '@Trait[Fatal]{Фатальное}' },
        { pattern: /`Фатальное прицеливание`/gi, replacement: '@Trait[FatalAim]{Фатальное прицеливание}' },
        { pattern: /`Фатальное прицеливание d10`/gi, replacement: '@Trait[FatalAimD10]{Фатальное прицеливание d10}' },
        { pattern: /`Фатальное прицеливание d12`/gi, replacement: '@Trait[FatalAimD12]{Фатальное прицеливание d12}' },
        { pattern: /`Фатальное d10`/gi, replacement: '@Trait[FatalD10]{Фатальное d10}' },
        { pattern: /`Фатальное d12`/gi, replacement: '@Trait[FatalD12]{Фатальное d12}' },
        { pattern: /`Фатальное d8`/gi, replacement: '@Trait[FatalD8]{Фатальное d8}' },
        { pattern: /`Страх[а-я]*`/gi, replacement: '@Trait[Fear]{Страх}' },
        { pattern: /`Фечлин`/gi, replacement: '@Trait[Fetchling]{Фечлин}' },
        { pattern: /`Фея`/gi, replacement: '@Trait[Fey]{Фея}' },
        { pattern: /`Прост[а-я]*`/gi, replacement: '@Trait[Simple]{Простая}' },
        { pattern: /`Бес`/gi, replacement: '@Trait[Fiend]{Бес}' },
        { pattern: /`Воин`/gi, replacement: '@Trait[Fighter]{Воин}' },
        { pattern: /`Figurehead`/gi, replacement: '@Trait[Figurehead]{Figurehead}' },
        { pattern: /`Точн[а-я]*`/gi, replacement: '@Trait[Finesse]{Точное}' },
        { pattern: /`Финишер`/gi, replacement: '@Trait[Finisher]{Финишер}' },
        { pattern: /`Конечн[а-я]*`/gi, replacement: '@Trait[Finite]{Конечный}' },
        { pattern: /`Огонь`/gi, replacement: '@Trait[Fire]{Огонь}' },
        { pattern: /`Флэшворп`/gi, replacement: '@Trait[Fleshwarp]{Флэшворп}' },
        { pattern: /`Гибк[а-я]*`/gi, replacement: '@Trait[Flexible]{Гибкий}' },
        { pattern: /`Размах`/gi, replacement: '@Trait[Flourish]{Размах}' },
        { pattern: /`Фокус`/gi, replacement: '@Trait[Focus]{Фокус}' },
        { pattern: /`Фокусирующ[а-я]*`/gi, replacement: '@Trait[Focused]{Фокусирующий}' },
        { pattern: /`Foldaway`/gi, replacement: '@Trait[Foldaway]{Foldaway}' },
        { pattern: /`Сила`/gi, replacement: '@Trait[Force]{Сила}' },
        { pattern: /`Силов[а-я]*`/gi, replacement: '@Trait[Forceful]{Силовое}' },
        { pattern: /`Формиец`/gi, replacement: '@Trait[Formian]{Формиец}' },
        { pattern: /`Удача`/gi, replacement: '@Trait[Fortune]{Удача}' },
        { pattern: /`Свободная рука`/gi, replacement: '@Trait[FreeHand]{Свободная рука}' },
        { pattern: /`Фулу`/gi, replacement: '@Trait[Fulu]{Фулу}' },
        { pattern: /`Грибков[а-я]*`/gi, replacement: '@Trait[Fungus]{Грибковый}' },
        { pattern: /`Гаджет`/gi, replacement: '@Trait[Gadget]{Гаджет}' },
        { pattern: /`Ганзи`/gi, replacement: '@Trait[Ganzi]{Ганзи}' },
        { pattern: /`Общ[а-я]*`/gi, replacement: '@Trait[General]{Общая}' },
        { pattern: /`Ген[а-я]*`/gi, replacement: '@Trait[Genie]{Гений}' },
        { pattern: /`Джинникин`/gi, replacement: '@Trait[Geniekin]{Джинникин}' },
        { pattern: /`Горан`/gi, replacement: '@Trait[Ghoran]{Горан}' },
        { pattern: /`Привидени[а-я]*`/gi, replacement: '@Trait[Ghost]{Привидение}' },
        { pattern: /`Упыр[а-я]*`/gi, replacement: '@Trait[Ghoul]{Упырь}' },
        { pattern: /`Ghul`/gi, replacement: '@Trait[Ghul]{Ghul}' },
        { pattern: /`Гигант[а-я]*`/gi, replacement: '@Trait[Giant]{Гигант}' },
        { pattern: /`Кхоло`/gi, replacement: '@Trait[Gnoll]{Кхоло}' },
        { pattern: /`Гном`/gi, replacement: '@Trait[Gnome]{Гном}' },
        { pattern: /`Гоблин[а-я]*`/gi, replacement: '@Trait[Goblin]{Гоблин}' },
        { pattern: /`Голем`/gi, replacement: '@Trait[Golem]{Голем}' },
        { pattern: /`Голома`/gi, replacement: '@Trait[Goloma]{Голома}' },
        { pattern: /`Приращени[а-я]*`/gi, replacement: '@Trait[Graft]{Приращение}' },
        { pattern: /`Захват`/gi, replacement: '@Trait[Grapple]{Захват}' },
        { pattern: /`Могильный рыцарь`/gi, replacement: '@Trait[Graveknight]{Могильный рыцарь}' },
        { pattern: /`Гремлин`/gi, replacement: '@Trait[Gremlin]{Гремлин}' },
        { pattern: /`Гримуар`/gi, replacement: '@Trait[Grimoire]{Гримуар}' },
        { pattern: /`Гриот`/gi, replacement: '@Trait[Grioth]{Гриот}' },
        { pattern: /`Гриппли`/gi, replacement: '@Trait[Grippli]{Гриппли}' },
        { pattern: /`Стрелок`/gi, replacement: '@Trait[Gunslinger]{Стрелок}' },
        { pattern: /`Карга`/gi, replacement: '@Trait[Hag]{Карга}' },
        { pattern: /`Безмятежн[а-я]*`/gi, replacement: '@Trait[Halcyon]{Безмятежная}' },
        { pattern: /`Полурослик`/gi, replacement: '@Trait[Halfling]{Полурослик}' },
        { pattern: /`Мешающее`/gi, replacement: '@Trait[Hampering]{Мешающее}' },
        { pattern: /`Ханту`/gi, replacement: '@Trait[Hantu]{Ханту}' },
        { pattern: /`Harnessed`/gi, replacement: '@Trait[Harnessed]{Harnessed}' },
        { pattern: /`Двор Харр[а-я]*`/gi, replacement: '@Trait[HarrowCourt]{Harrow Court}' },
        { pattern: /`Призрак`/gi, replacement: '@Trait[Haunt]{Призрак}' },
        { pattern: /`Исцелен[а-я]*`/gi, replacement: '@Trait[Healing]{Исцеление}' },
        { pattern: /`Вестник`/gi, replacement: '@Trait[Herald]{Вестник}' },
        { pattern: /`Наследие`/gi, replacement: '@Trait[Heritage]{Наследие}' },
        { pattern: /`Сглаз`/gi, replacement: '@Trait[Hex]{Сглаз}' },
        { pattern: /`Hindering`/gi, replacement: '@Trait[Hindering]{Hindering}' },
        { pattern: /`Хобгоблин`/gi, replacement: '@Trait[Hobgoblin]{Хобгоблин}' },
        { pattern: /`Свято[а-я]*`/gi, replacement: '@Trait[Holy]{Святой}' },
        { pattern: /`Хрингар`/gi, replacement: '@Trait[Hryngar]{Хрингар}' },
        { pattern: /`Человек[а-я]*`/gi, replacement: '@Trait[Human]{Человек}' },
        { pattern: /`Гуманоид[а-я]*`/gi, replacement: '@Trait[Humanoid]{Гуманоид}' },
        { pattern: /`Ифрит`/gi, replacement: '@Trait[Ifrit]{Ифрит}' },
        { pattern: /`Икешти`/gi, replacement: '@Trait[Ikeshti]{Икешти}' },
        { pattern: /`Иллюзи[а-я]*`/gi, replacement: '@Trait[Illusion]{Иллюзия}' },
        { pattern: /`Implanted`/gi, replacement: '@Trait[Implanted]{Implanted}' },
        { pattern: /`Импульс`/gi, replacement: '@Trait[Impulse]{Импульс}' },
        { pattern: /`Недееспособност[а-я]*`/gi, replacement: '@Trait[Incapacitation]{Недееспособность}' },
        { pattern: /`Инкарнац[а-я]*`/gi, replacement: '@Trait[Incarnate]{Инкарнация}' },
        { pattern: /`Бестелесн[а-я]*`/gi, replacement: '@Trait[Incorporeal]{Бестелесный}' },
        { pattern: /`Неминуем[а-я]*`/gi, replacement: '@Trait[Inevitable]{Неминуемый}' },
        { pattern: /`Насыщенн[а-я]*`/gi, replacement: '@Trait[Infused]{Насыщенный}' },
        { pattern: /`Нагнетани[а-я]*`/gi, replacement: '@Trait[Infusion]{Нагнетание}' },
        { pattern: /`Глотаем[а-я]*`/gi, replacement: '@Trait[Ingested]{Глотаемый}' },
        { pattern: /`Вдыхаем[а-я]*`/gi, replacement: '@Trait[Inhaled]{Вдыхаемый}' },
        { pattern: /`Инъекционн[а-я]*`/gi, replacement: '@Trait[Injection]{Инъекционный}' },
        { pattern: /`Ранение`/gi, replacement: '@Trait[Injury]{Ранение}' },
        { pattern: /`Разумн[а-я]*`/gi, replacement: '@Trait[Intelligent]{Разумный}' },
        { pattern: /`Взаимодейств[а-я]*`/gi, replacement: '@Trait[Interact]{Взаимодействовать}' },
        { pattern: /`Изобретатель`/gi, replacement: '@Trait[Inventor]{Изобретатель}' },
        { pattern: /`Инвестируем[а-я]*`/gi, replacement: '@Trait[Invested]{Инвестируемый}' },
        { pattern: /`Сыщик`/gi, replacement: '@Trait[Investigator]{Сыщик}' },
        { pattern: /`Кавалерийск[а-я]*`/gi, replacement: '@Trait[Jousting]{Кавалерийское}' },
        { pattern: /`Кавалерийское d6`/gi, replacement: '@Trait[JoustingD6]{Кавалерийское d6}' },
        { pattern: /`Кайдзю`/gi, replacement: '@Trait[Kaiju]{Кайдзю}' },
        { pattern: /`Ками`/gi, replacement: '@Trait[Kami]{Ками}' },
        { pattern: /`Кашриши`/gi, replacement: '@Trait[Kashrishi]{Кашриши}' },
        { pattern: /`Отдача`/gi, replacement: '@Trait[Kickback]{Отдача}' },
        { pattern: /`Кинетик`/gi, replacement: '@Trait[Kineticist]{Кинетик}' },
        { pattern: /`Королевство`/gi, replacement: '@Trait[Kingdom]{Королевство}' },
        { pattern: /`Кицунэ`/gi, replacement: '@Trait[Kitsune]{Кицунэ}' },
        { pattern: /`Кобольд`/gi, replacement: '@Trait[Kobold]{Кобольд}' },
        { pattern: /`Ковинт`/gi, replacement: '@Trait[Kovintus]{Ковинт}' },
        { pattern: /`Laminar`/gi, replacement: '@Trait[Laminar]{Laminar}' },
        { pattern: /`Launching`/gi, replacement: '@Trait[Launching]{Launching}' },
        { pattern: /`Леш[а-я]*`/gi, replacement: '@Trait[Leshy]{Леший}' },
        { pattern: /`Свет`/gi, replacement: '@Trait[Light]{Свет}' },
        { pattern: /`Lilu`/gi, replacement: '@Trait[Lilu]{Lilu}' },
        { pattern: /`Род`/gi, replacement: '@Trait[Lineage]{Род}' },
        { pattern: /`Языков[а-я]*`/gi, replacement: '@Trait[Linguistic]{Языковой}' },
        { pattern: /`Литания`/gi, replacement: '@Trait[Litany]{Литания}' },
        { pattern: /`Людоящер[а-я]*`/gi, replacement: '@Trait[Lizardfolk]{Людоящер}' },
        { pattern: /`Атамару`/gi, replacement: '@Trait[Locathah]{Атамару}' },
        { pattern: /`Lozenge`/gi, replacement: '@Trait[Lozenge]{Lozenge}' },
        { pattern: /`Магия`/gi, replacement: '@Trait[Magic]{Магия}' },
        { pattern: /`Магическ[а-я]*`/gi, replacement: '@Trait[Magical]{Магический}' },
        { pattern: /`Магус`/gi, replacement: '@Trait[Magus]{Магус}' },
        { pattern: /`Воздейств[а-я]*`/gi, replacement: '@Trait[Manipulate]{Воздействие}' },
        { pattern: /`Механическ[а-я]*`/gi, replacement: '@Trait[Mechanical]{Механический}' },
        { pattern: /`Ментальн[а-я]*`/gi, replacement: '@Trait[Mental]{Ментальный}' },
        { pattern: /`Мерфолк`/gi, replacement: '@Trait[Merfolk]{Мерфолк}' },
        { pattern: /`Металл`/gi, replacement: '@Trait[Metal]{Металл}' },
        { pattern: /`Неразумн[а-я]*`/gi, replacement: '@Trait[Mindless]{Неразумный}' },
        { pattern: /`Сдвиг разума`/gi, replacement: '@Trait[Mindshift]{Сдвиг разума}' },
        { pattern: /`Миньон`/gi, replacement: '@Trait[Minion]{Миньон}' },
        { pattern: /`Минотавр`/gi, replacement: '@Trait[Minotaur]{Минотавр}' },
        { pattern: /`Неудач[а-я]*`/gi, replacement: '@Trait[Misfortune]{Неудача}' },
        { pattern: /`Эффекты неудачи`/gi, replacement: '@Trait[MisfortuneEffects]{Эффекты неудачи}' },
        { pattern: /`Missive`/gi, replacement: '@Trait[Missive]{Missive}' },
        { pattern: /`Модификац[а-я]*`/gi, replacement: '@Trait[Modification]{Модификация}' },
        { pattern: /`Модульное Д, К или Р`/gi, replacement: '@Trait[Modular]{Модульное Д, К или Р}' },
        { pattern: /`Наблюдатель`/gi, replacement: '@Trait[Monitor]{Наблюдатель}' },
        { pattern: /`Монах`/gi, replacement: '@Trait[Monk]{Монах}' },
        { pattern: /`Морлок`/gi, replacement: '@Trait[Morlock]{Морлок}' },
        { pattern: /`Трансформация`/gi, replacement: '@Trait[Morph]{Трансформация}' },
        { pattern: /`Мортик`/gi, replacement: '@Trait[Mortic]{Мортик}' },
        { pattern: /`Стационарн[а-я]*`/gi, replacement: '@Trait[Mounted]{Стационарное}' },
        { pattern: /`Движени[а-я]*`/gi, replacement: '@Trait[Move]{Движение}' },
        { pattern: /`Мультикласс`/gi, replacement: '@Trait[Multiclass]{Мультикласс}' },
        { pattern: /`Мумия`/gi, replacement: '@Trait[Mummy]{Мумия}' },
        { pattern: /`Мунавр`/gi, replacement: '@Trait[Munavri]{Мунавр}' },
        { pattern: /`Мутаген`/gi, replacement: '@Trait[Mutagen]{Мутаген}' },
        { pattern: /`Мутант`/gi, replacement: '@Trait[Mutant]{Мутант}' },
        { pattern: /`Наари`/gi, replacement: '@Trait[Naari]{Наари}' },
        { pattern: /`Нагаджи`/gi, replacement: '@Trait[Nagaji]{Нагаджи}' },
        { pattern: /`Нефилим`/gi, replacement: '@Trait[Nephilim]{Нефилим}' },
        { pattern: /`Nindoru`/gi, replacement: '@Trait[Nindoru]{Nindoru}' },
        { pattern: /`Шумн[а-я]*`/gi, replacement: '@Trait[Noisy]{Шумный}' },
        { pattern: /`Несмертельн[а-я]*`/gi, replacement: '@Trait[Nonlethal]{Несмертельное}' },
        { pattern: /`Нимфа`/gi, replacement: '@Trait[Nymph]{Нимфа}' },
        { pattern: /`Клятва`/gi, replacement: '@Trait[Oath]{Клятва}' },
        { pattern: /`Оккультн[а-я]*`/gi, replacement: '@Trait[Occult]{Оккультный}' },
        { pattern: /`Масло`/gi, replacement: '@Trait[Oil]{Масло}' },
        { pattern: /`Обонятельн[а-я]*`/gi, replacement: '@Trait[Olfactory]{Обонятельный}' },
        { pattern: /`Они`/gi, replacement: '@Trait[Oni]{Они}' },
        { pattern: /`Слиз[а-я]*`/gi, replacement: '@Trait[Ooze]{Слизь}' },
        { pattern: /`Оракул`/gi, replacement: '@Trait[Oracle]{Оракул}' },
        { pattern: /`Орк`/gi, replacement: '@Trait[Orc]{Орк}' },
        { pattern: /`Ореад`/gi, replacement: '@Trait[Oread]{Ореад}' },
        { pattern: /`Переполнение`/gi, replacement: '@Trait[Overflow]{Переполнение}' },
        { pattern: /`Паарайдар`/gi, replacement: '@Trait[Paaridar]{Паарайдар}' },
        { pattern: /`Парирован[а-я]*`/gi, replacement: '@Trait[Parry]{Парирование}' },
        { pattern: /`Повсеместная магия`/gi, replacement: '@Trait[PervasiveMagic]{Повсеместная магия}' },
        { pattern: /`Проситель`/gi, replacement: '@Trait[Petitioner]{Проситель}' },
        { pattern: /`Фантом`/gi, replacement: '@Trait[Phantom]{Фантом}' },
        { pattern: /`Физическ[а-я]*`/gi, replacement: '@Trait[Physical]{Физический}' },
        { pattern: /`Колющ[а-я]*`/gi, replacement: '@Trait[Piercing]{Колющий}' },
        { pattern: /`Растен[а-я]*`/gi, replacement: '@Trait[Plant]{Растение}' },
        { pattern: /`Яд`/gi, replacement: '@Trait[Poison]{Яд}' },
        { pattern: /`Полиморф`/gi, replacement: '@Trait[Polymorph]{Полиморф}' },
        { pattern: /`Ponderous`/gi, replacement: '@Trait[Ponderous]{Ponderous}' },
        { pattern: /`Кукла`/gi, replacement: '@Trait[Poppet]{Кукла}' },
        { pattern: /`Переносн[а-я]*`/gi, replacement: '@Trait[Portable]{Переносное}' },
        { pattern: /`Одержимость`/gi, replacement: '@Trait[Possession]{Одержимость}' },
        { pattern: /`Зелье`/gi, replacement: '@Trait[Potion]{Зелье}' },
        { pattern: /`Драгоценн[а-я]*`/gi, replacement: '@Trait[Precious]{Драгоценный}' },
        { pattern: /`Предсказан[а-я]*`/gi, replacement: '@Trait[Prediction]{Предсказание}' },
        { pattern: /`Натиск`/gi, replacement: '@Trait[Press]{Натиск}' },
        { pattern: /`Природн[а-я]*`/gi, replacement: '@Trait[Primal]{Природный}' },
        { pattern: /`Processed`/gi, replacement: '@Trait[Processed]{Processed}' },
        { pattern: /`Тягов[а-я]*`/gi, replacement: '@Trait[Propulsive]{Тяговое}' },
        { pattern: /`Протей`/gi, replacement: '@Trait[Protean]{Протей}' },
        { pattern: /`Психика`/gi, replacement: '@Trait[Psyche]{Психика}' },
        { pattern: /`Экстрасенс`/gi, replacement: '@Trait[Psychic]{Экстрасенс}' },
        { pattern: /`Психопомп[а-я]*`/gi, replacement: '@Trait[Psychopomp]{Психопомп}' },
        { pattern: /`Клиппот[а-я]*`/gi, replacement: '@Trait[Qlippoth]{Клиппот}' },
        { pattern: /`Радиация`/gi, replacement: '@Trait[Radiation]{Радиация}' },
        { pattern: /`Ярость`/gi, replacement: '@Trait[Rage]{Ярость}' },
        { pattern: /`Ракшаса`/gi, replacement: '@Trait[Rakshasa]{Ракшаса}' },
        { pattern: /`Дистанция`/gi, replacement: '@Trait[Range]{Дистанция}' },
        { pattern: /`Дистанционное опрокидывание`/gi, replacement: '@Trait[RangedTrip]{Дистанционное опрокидывание}' },
        { pattern: /`Рейнджер`/gi, replacement: '@Trait[Ranger]{Рейнджер}' },
        { pattern: /`Редк[а-я]*`/gi, replacement: '@Trait[Rare]{Редкий}' },
        { pattern: /`Ратаджин`/gi, replacement: '@Trait[Ratajin]{Ратаджин}' },
        { pattern: /`Крысолюд`/gi, replacement: '@Trait[Ratfolk]{Крысолюд}' },
        { pattern: /`Сносящ[а-я]*`/gi, replacement: '@Trait[Razing]{Сносящий}' },
        { pattern: /`Длинн[а-я]*`/gi, replacement: '@Trait[Reach]{Длинное}' },
        { pattern: /`Безрассудство`/gi, replacement: '@Trait[Reckless]{Безрассудство}' },
        { pattern: /`Recovery`/gi, replacement: '@Trait[Recovery]{Recovery}' },
        { pattern: /`Отражение`/gi, replacement: '@Trait[Reflection]{Отражение}' },
        { pattern: /`Reincarnated`/gi, replacement: '@Trait[Reincarnated]{Reincarnated}' },
        { pattern: /`Реликвия`/gi, replacement: '@Trait[Relic]{Реликвия}' },
        { pattern: /`Многозарядн[а-я]*`/gi, replacement: '@Trait[Repeating]{Многозарядное}' },
        { pattern: /`Резонирующее`/gi, replacement: '@Trait[Resonant]{Резонирующее}' },
        { pattern: /`Откровение`/gi, replacement: '@Trait[Revelation]{Откровение}' },
        { pattern: /`Плут`/gi, replacement: '@Trait[Rogue]{Плут}' },
        { pattern: /`Саггорак`/gi, replacement: '@Trait[Saggorak]{Саггорак}' },
        { pattern: /`Сахкил`/gi, replacement: '@Trait[Sahkil]{Сахкил}' },
        { pattern: /`Самсар`/gi, replacement: '@Trait[Samsaran]{Самсар}' },
        { pattern: /`Освященн[а-я]*`/gi, replacement: '@Trait[Sanctified]{Освященный}' },
        { pattern: /`Разброс`/gi, replacement: '@Trait[Scatter]{Разброс}' },
        { pattern: /`Разброс 10`/gi, replacement: '@Trait[Scatter10]{Разброс 10}' },
        { pattern: /`Разброс 15`/gi, replacement: '@Trait[Scatter15]{Разброс 15}' },
        { pattern: /`Разброс 20`/gi, replacement: '@Trait[Scatter20]{Разброс 20}' },
        { pattern: /`Разброс 5`/gi, replacement: '@Trait[Scatter5]{Разброс 5}' },
        { pattern: /`Свиток`/gi, replacement: '@Trait[Scroll]{Свиток}' },
        { pattern: /`Видение`/gi, replacement: '@Trait[Scrying]{Видение}' },
        { pattern: /`Морской дьявол`/gi, replacement: '@Trait[SeaDevil]{Морской дьявол}' },
        { pattern: /`Тайн[а-я]*`/gi, replacement: '@Trait[Secret]{Тайна}' },
        { pattern: /`Sedacthy`/gi, replacement: '@Trait[Sedacthy]{Sedacthy}' },
        { pattern: /`Змеелюд`/gi, replacement: '@Trait[Serpentfolk]{Змеелюд}' },
        { pattern: /`Сьюгати`/gi, replacement: '@Trait[Seugathi]{Сьюгати}' },
        { pattern: /`Вшитое в одежду`/gi, replacement: '@Trait[SewnIntoClothing]{Вшитое в одежду}' },
        { pattern: /`Шабти`/gi, replacement: '@Trait[Shabti]{Шабти}' },
        { pattern: /`Тень`/gi, replacement: '@Trait[Shadow]{Тень}' },
        { pattern: /`Шиск`/gi, replacement: '@Trait[Shisk]{Шиск}' },
        { pattern: /`Шобхад`/gi, replacement: '@Trait[Shobhad]{Шобхад}' },
        { pattern: /`Шуни`/gi, replacement: '@Trait[Shoony]{Шуни}' },
        { pattern: /`Толчок`/gi, replacement: '@Trait[Shove]{Толчок}' },
        { pattern: /`Сиктемпора`/gi, replacement: '@Trait[Siktempora]{Сиктемпора}' },
        { pattern: /`Скелет`/gi, replacement: '@Trait[Skeleton]{Скелет}' },
        { pattern: /`Скельм`/gi, replacement: '@Trait[Skelm]{Скельм}' },
        { pattern: /`Навык`/gi, replacement: '@Trait[Skill]{Навык}' },
        { pattern: /`Скалк`/gi, replacement: '@Trait[Skulk]{Скалк}' },
        { pattern: /`Рубящ[а-я]*`/gi, replacement: '@Trait[Slashing]{Рубящий}' },
        { pattern: /`Сон`/gi, replacement: '@Trait[Sleep]{Сон}' },
        { pattern: /`Силок`/gi, replacement: '@Trait[Snare]{Силок}' },
        { pattern: /`Публичн[а-я]*`/gi, replacement: '@Trait[Social]{Публичный}' },
        { pattern: /`Звуковой`/gi, replacement: '@Trait[Sonic]{Звуковой}' },
        { pattern: /`Чародей`/gi, replacement: '@Trait[Sorcerer]{Чародей}' },
        { pattern: /`Одушевлённ[а-я]*`/gi, replacement: '@Trait[Soulbound]{Одушевлённый}' },
        { pattern: /`Отражение заклинан[а-я]*`/gi, replacement: '@Trait[SpellDeflection]{Отражение заклинаний}' },
        { pattern: /`Spellgun`/gi, replacement: '@Trait[Spellgun]{Spellgun}' },
        { pattern: /`Сердце заклинания`/gi, replacement: '@Trait[Spellheart]{Сердце заклинания}' },
        { pattern: /`Формирование заклинания`/gi, replacement: '@Trait[Spellshape]{Формирование заклинания}' },
        { pattern: /`Магический стрелок`/gi, replacement: '@Trait[Spellshot]{Магический стрелок}' },
        { pattern: /`Дух`/gi, replacement: '@Trait[Spirit]{Дух}' },
        { pattern: /`Брызги`/gi, replacement: '@Trait[Splash]{Брызги}' },
        { pattern: /`Брызги 10 фт`/gi, replacement: '@Trait[Splash10]{Брызги 10 фт}' },
        { pattern: /`Sporeborn`/gi, replacement: '@Trait[Sporeborn]{Sporeborn}' },
        { pattern: /`Спригган`/gi, replacement: '@Trait[Spriggan]{Спригган}' },
        { pattern: /`Спрайт`/gi, replacement: '@Trait[Sprite]{Спрайт}' },
        { pattern: /`Посох`/gi, replacement: '@Trait[Staff]{Посох}' },
        { pattern: /`Выносливость`/gi, replacement: '@Trait[Stamina]{Выносливость}' },
        { pattern: /`Стойк[а-я]*`/gi, replacement: '@Trait[Stance]{Стойка}' },
        { pattern: /`Паров[а-я]*`/gi, replacement: '@Trait[Steam]{Паровое}' },
        { pattern: /`Стено`/gi, replacement: '@Trait[Stheno]{Стено}' },
        { pattern: /`Стрикс`/gi, replacement: '@Trait[Strix]{Стрикс}' },
        { pattern: /`Строение`/gi, replacement: '@Trait[Structure]{Строение}' },
        { pattern: /`Субъективная гравитация`/gi, replacement: '@Trait[SubjectiveGravity]{Субъективная гравитация}' },
        { pattern: /`Незаметн[а-я]*`/gi, replacement: '@Trait[Subtle]{Незаметный}' },
        { pattern: /`Сули`/gi, replacement: '@Trait[Suli]{Сули}' },
        { pattern: /`Призыв`/gi, replacement: '@Trait[Summon]{Призыв}' },
        { pattern: /`Призванн[а-я]*`/gi, replacement: '@Trait[Summoned]{Призванный}' },
        { pattern: /`Призыватель`/gi, replacement: '@Trait[Summoner]{Призыватель}' },
        { pattern: /`Суркай`/gi, replacement: '@Trait[Surki]{Суркай}' },
        { pattern: /`Рой`/gi, replacement: '@Trait[Swarm]{Рой}' },
        { pattern: /`Сорвиголова`/gi, replacement: '@Trait[Swashbuckler]{Сорвиголова}' },
        { pattern: /`Размах`/gi, replacement: '@Trait[Sweep]{Размах}' },
        { pattern: /`Сильф`/gi, replacement: '@Trait[Sylph]{Сильф}' },
        { pattern: /`Талисман`/gi, replacement: '@Trait[Talisman]{Талисман}' },
        { pattern: /`Талос`/gi, replacement: '@Trait[Talos]{Талос}' },
        { pattern: /`Тандем`/gi, replacement: '@Trait[Tandem]{Тандем}' },
        { pattern: /`Тэйн`/gi, replacement: '@Trait[Tane]{Тэйн}' },
        { pattern: /`Танггал`/gi, replacement: '@Trait[Tanggal]{Танггал}' },
        { pattern: /`Тануки`/gi, replacement: '@Trait[Tanuki]{Тануки}' },
        { pattern: /`Татуировка`/gi, replacement: '@Trait[Tattoo]{Татуировка}' },
        { pattern: /`Татуирован на теле`/gi, replacement: '@Trait[TattooedOnTheBody]{Татуирован на теле}' },
        { pattern: /`Чай`/gi, replacement: '@Trait[Tea]{Чай}' },
        { pattern: /`Технология`/gi, replacement: '@Trait[Tech]{Технология}' },
        { pattern: /`Технологическ[а-я]*`/gi, replacement: '@Trait[Technological]{Технологическое}' },
        { pattern: /`Телепатия`/gi, replacement: '@Trait[Telepathy]{Телепатия}' },
        { pattern: /`Телепортация`/gi, replacement: '@Trait[Teleportation]{Телепортация}' },
        { pattern: /`Тэнгу`/gi, replacement: '@Trait[Tengu]{Тэнгу}' },
        { pattern: /`Привязанн[а-я]*`/gi, replacement: '@Trait[Tethered]{Привязанное}' },
        { pattern: /`Тауматург`/gi, replacement: '@Trait[Thaumaturge]{Тауматург}' },
        { pattern: /`Метательн[а-я]*`/gi, replacement: '@Trait[Thrown]{Метательное}' },
        { pattern: /`Время`/gi, replacement: '@Trait[Time]{Время}' },
        { pattern: /`Титан`/gi, replacement: '@Trait[Titan]{Титан}' },
        { pattern: /`Touched`/gi, replacement: '@Trait[Touched]{Touched}' },
        { pattern: /`Training`/gi, replacement: '@Trait[Training]{Training}' },
        { pattern: /`Ловушка`/gi, replacement: '@Trait[Trap]{Ловушка}' },
        { pattern: /`Испытание`/gi, replacement: '@Trait[Trial]{Испытание}' },
        { pattern: /`Опрокидывание`/gi, replacement: '@Trait[Trip]{Опрокидывание}' },
        { pattern: /`Тролль`/gi, replacement: '@Trait[Troll]{Тролль}' },
        { pattern: /`Отряд`/gi, replacement: '@Trait[Troop]{Отряд}' },
        { pattern: /`Истинное имя`/gi, replacement: '@Trait[TrueName]{Истинное имя}' },
        { pattern: /`Парн[а-я]*`/gi, replacement: '@Trait[Twin]{Парное}' },
        { pattern: /`Двуручн[а-я]*`/gi, replacement: '@Trait[TwoHand]{Двуручное}' },
        { pattern: /`Двуручное d10`/gi, replacement: '@Trait[TwoHandD10]{Двуручное d10}' },
        { pattern: /`Двуручное d12`/gi, replacement: '@Trait[TwoHandD12]{Двуручное d12}' },
        { pattern: /`Двуручное d6`/gi, replacement: '@Trait[TwoHandD6]{Двуручное d6}' },
        { pattern: /`Двуручное d8`/gi, replacement: '@Trait[TwoHandD8]{Двуручное d8}' },
        { pattern: /`Безоружн[а-я]*`/gi, replacement: '@Trait[Unarmed]{Безоружное}' },
        { pattern: /`Необычн[а-я]*`/gi, replacement: '@Trait[Uncommon]{Необычный}' },
        { pattern: /`Нежить`/gi, replacement: '@Trait[Undead]{Нежить}' },
        { pattern: /`Ундина`/gi, replacement: '@Trait[Undine]{Ундина}' },
        { pattern: /`Нечестив[а-я]*`/gi, replacement: '@Trait[Unholy]{Нечестивый}' },
        { pattern: /`Уникальн[а-я]*`/gi, replacement: '@Trait[Unique]{Уникальный}' },
        { pattern: /`Нестабильн[а-я]*`/gi, replacement: '@Trait[Unstable]{Нестабильный}' },
        { pattern: /`Без типа`/gi, replacement: '@Trait[Untyped]{Без типа}' },
        { pattern: /`Урдефан`/gi, replacement: '@Trait[Urdefhan]{Урдефан}' },
        { pattern: /`Вампир`/gi, replacement: '@Trait[Vampire]{Вампир}' },
        { pattern: /`Ванар`/gi, replacement: '@Trait[Vanara]{Ванар}' },
        { pattern: /`Vehicular`/gi, replacement: '@Trait[Vehicular]{Vehicular}' },
        { pattern: /`Вельстрак`/gi, replacement: '@Trait[Velstrac]{Вельстрак}' },
        { pattern: /`Venomous`/gi, replacement: '@Trait[Venomous]{Venomous}' },
        { pattern: /`Универсальн[а-я]*`/gi, replacement: '@Trait[Versatile]{Универсальное}' },
        { pattern: /`Пустота`/gi, replacement: '@Trait[Void]{Пустота}' },
        { pattern: /`Залпов[а-я]*`/gi, replacement: '@Trait[Volley]{Залповое}' },
        { pattern: /`Вода`/gi, replacement: '@Trait[Water]{Вода}' },
        { pattern: /`Ваян`/gi, replacement: '@Trait[Wayang]{Ваян}' },
        { pattern: /`Оружие`/gi, replacement: '@Trait[Weapons]{Оружие}' },
        { pattern: /`Оборотень`/gi, replacement: '@Trait[Werecreature]{Оборотень}' },
        { pattern: /`Умертвие`/gi, replacement: '@Trait[Wight]{Умертвие}' },
        { pattern: /`Wild Hunt`/gi, replacement: '@Trait[WildHunt]{Wild Hunt}' },
        { pattern: /`Ведьма`/gi, replacement: '@Trait[Witch]{Ведьма}' },
        { pattern: /`Волшебник`/gi, replacement: '@Trait[Wizard]{Волшебник}' },
        { pattern: /`Дерево`/gi, replacement: '@Trait[Wood]{Дерево}' },
        { pattern: /`Носим[а-я]*`/gi, replacement: '@Trait[Worn]{Носимый}' },
        { pattern: /`Амулет`/gi, replacement: '@Trait[WornAmulet]{Амулет}' },
        { pattern: /`Лодыжки`/gi, replacement: '@Trait[WornAnklets]{Лодыжки}' },
        { pattern: /`Нарукавники`/gi, replacement: '@Trait[WornArmbands]{Нарукавники}' },
        { pattern: /`Рюкзак`/gi, replacement: '@Trait[WornBackpack]{Рюкзак}' },
        { pattern: /`Броня животного`/gi, replacement: '@Trait[WornBarding]{Броня животного}' },
        { pattern: /`Пояс`/gi, replacement: '@Trait[WornBelt]{Пояс}' },
        { pattern: /`Поясная сумка`/gi, replacement: '@Trait[WornBeltPouch]{Поясная сумка}' },
        { pattern: /`Worn Boots`/gi, replacement: '@Trait[WornBoots]{Worn Boots}' },
        { pattern: /`Браслет`/gi, replacement: '@Trait[WornBracelet]{Браслет}' },
        { pattern: /`Браслеты`/gi, replacement: '@Trait[WornBracers]{Браслеты}' },
        { pattern: /`Worn Cap`/gi, replacement: '@Trait[WornCap]{Worn Cap}' },
        { pattern: /`Worn Cape`/gi, replacement: '@Trait[WornCape]{Worn Cape}' },
        { pattern: /`Диадема`/gi, replacement: '@Trait[WornCirclet]{Диадема}' },
        { pattern: /`Накидка`/gi, replacement: '@Trait[WornCloak]{Накидка}' },
        { pattern: /`Одежда`/gi, replacement: '@Trait[WornClothing]{Одежда}' },
        { pattern: /`Ошейник`/gi, replacement: '@Trait[WornCollar]{Ошейник}' },
        { pattern: /`Корона`/gi, replacement: '@Trait[WornCrown]{Корона}' },
        { pattern: /`Эполеты`/gi, replacement: '@Trait[WornEpaulet]{Эполеты}' },
        { pattern: /`Окуляр`/gi, replacement: '@Trait[WornEyepiece]{Окуляр}' },
        { pattern: /`Worn Footwear`/gi, replacement: '@Trait[WornFootwear]{Worn Footwear}' },
        { pattern: /`Одежда`/gi, replacement: '@Trait[WornGarment]{Одежда}' },
        { pattern: /`Перчатки`/gi, replacement: '@Trait[WornGloves]{Перчатки}' },
        { pattern: /`Головной убор`/gi, replacement: '@Trait[WornHeadwear]{Головной убор}' },
        { pattern: /`Подковы`/gi, replacement: '@Trait[WornHorseshoes]{Подковы}' },
        { pattern: /`Маска`/gi, replacement: '@Trait[WornMask]{Маска}' },
        { pattern: /`Ожерелье`/gi, replacement: '@Trait[WornNecklace]{Ожерелье}' },
        { pattern: /`Поясной предмет`/gi, replacement: '@Trait[WornOnBelt]{Поясной предмет}' },
        { pattern: /`Запястья`/gi, replacement: '@Trait[WornOnWrists]{Запястья}' },
        { pattern: /`Кольцо`/gi, replacement: '@Trait[WornRing]{Кольцо}' },
        { pattern: /`Седло`/gi, replacement: '@Trait[WornSaddle]{Седло}' },
        { pattern: /`Обувь`/gi, replacement: '@Trait[WornShoes]{Обувь}' },
        { pattern: /`Рэйф`/gi, replacement: '@Trait[Wraith]{Рэйф}' },
        { pattern: /`Wraithvine`/gi, replacement: '@Trait[Wraithvine]{Wraithvine}' },
        { pattern: /`Вирвуд`/gi, replacement: '@Trait[Wyrwood]{Вирвуд}' },
        { pattern: /`Зулгат`/gi, replacement: '@Trait[Xulgath]{Зулгат}' },
        { pattern: /`Зомби`/gi, replacement: '@Trait[Zombie]{Зомби}' },
        { pattern: /`Маленьк[а-я]*`/gi, replacement: '@Trait[Small]{Маленький}' },
        { pattern: /`Средн[а-я]*`/gi, replacement: '@Trait[Medium]{Средний}' },
        { pattern: /`Больш[а-я]*`/gi, replacement: '@Trait[Large]{Большой}' },
        { pattern: /`Крошечн[а-я]*`/gi, replacement: '@Trait[Tiny]{Крошечный}' },
        { pattern: /`Огромн[а-я]*`/gi, replacement: '@Trait[Huge]{Огромный}' },
        { pattern: /`Исполинск[а-я]*`/gi, replacement: '@Trait[Gargantuan]{Исполинский}' },

        { pattern: /`Нейтрал[а-я]*`/gi, replacement: '@Trait[Neutral]{Нейтральный}' },
        { pattern: /`Слаб[а-я]*`/gi, replacement: '@Trait[Weak]{Слабый}' },
        { pattern: /`Элитн[а-я]*`/gi, replacement: '@Trait[Elite]{Элитный}' },

        // Изменения в англ
        { pattern: /Maximum Duration\<\/strong\> ([0-9])/gi, replacement: 'Макс.Продолж.:\<\/strong\> $1' },
        { pattern: /Trigger\<\/strong\>/gi, replacement: 'Триггер:\<\/strong\>' },
        { pattern: /\<strong\>Effect\<\/strong\> /gi, replacement: '' },
        { pattern: /(?<!Critical )Success\<\/strong\>/gi, replacement: 'Успех:\<\/strong\>' },
        { pattern: /(?<!Critical )Failure\<\/strong\>/gi, replacement: 'Провал:\<\/strong\>' },
        { pattern: /Critical Success\<\/strong\>/gi, replacement: 'Крит.Успех:\<\/strong\>' },
        { pattern: /Critical Failure\<\/strong\>/gi, replacement: 'Крит.Провал:\<\/strong\>' },
        { pattern: /As failure,/gi, replacement: 'Как Провал,' },
        { pattern: /Requirements\<\/strong\>/gi, replacement: 'Требования:\<\/strong\>' },
        { pattern: /Frequency\<\/strong\>/gi, replacement: 'Частота:\<\/strong\>' },
        { pattern: /Onset\<\/strong\>/gi, replacement: 'Возникновение:\<\/strong\>' },
        { pattern: /Saving Throw\<\/strong\>/gi, replacement: 'Спасбросок:\<\/strong\>' },
        { pattern: /Activate\<\/strong\>/gi, replacement: 'Активация:\<\/strong\>' },




        { pattern: /The target is unaffected/gi, replacement: 'Цель невредима' },
        { pattern: /The target is/gi, replacement: 'Цель получает' },
        { pattern: /The creature takes no damage/gi, replacement: 'Существо не получает урона' },
        { pattern: /The creature takes half damage./gi, replacement: 'Существо получает половину урона' },
        { pattern: /The creature takes full damage/gi, replacement: 'Существо получает полный урон' },
        { pattern: /The creature takes double damage/gi, replacement: 'Существо получает двойной урон' },
        { pattern: /The creature takes/gi, replacement: 'Существо получает' },
        { pattern: /The target takes no damage/gi, replacement: 'Цель не получает урона' },
        { pattern: /The target takes half damage./gi, replacement: 'Цель получает половину урона' },
        { pattern: /The target takes full damage/gi, replacement: 'Цель получает полный урон' },
        { pattern: /The target takes double damage/gi, replacement: 'Цель получает двойной урон' },
        { pattern: /The target takes/gi, replacement: 'Цель получает' },
        { pattern: /until the end of their next turn/gi, replacement: 'до конца своего следующего хода' },

        { pattern: /once per day/gi, replacement: '1/День' },
        { pattern: /, plus overcharge/gi, replacement: ', плюс Перегрузка' },
        { pattern: /The creature is unaffected/gi, replacement: 'Существо невредимо' },
        { pattern: /The creature is/gi, replacement: 'Существо получает' },
        { pattern: /that creature is temporarily immune/gi, replacement: 'существо получает временно иммунитет' },
        { pattern: /A creature that succeeds at its save is temporarily immune/gi, replacement: 'Существо получившее успех спасброска получает временно иммунитет' },
        { pattern: /multiple attack penalty/gi, replacement: 'Штраф Множественных Атак' },
        { pattern: /Damage depends on the number of actions/gi, replacement: 'Урон зависит от количества действий' },

        { pattern: /\]\{Dazzled\}/gi, replacement: '\]\{Ослеплен\}' },
        { pattern: /\]\{Blinded\}/gi, replacement: '\]\{Слепота\}' },
        { pattern: /\]\{Immobilized\}/gi, replacement: '\]\{Обездвижен\}' },
        { pattern: /\]\{Confused\}/gi, replacement: '\]\{Замешательство\}' },
        { pattern: /\]\{Paralyzed\}/gi, replacement: '\]\{Парализован\}' },
        { pattern: /\]\{Unconscious\}/gi, replacement: '\]\{Без сознания\}' },
        { pattern: /\]\{Fascinated\}/gi, replacement: '\]\{Заворожен\}' },
        { pattern: /\]\{Fleeing\}/gi, replacement: '\]\{Бегство\}' },
        { pattern: /\]\{Flat-Footed\}/gi, replacement: '\]\{Застиг.Врасплох\}' },
        { pattern: /\]\{Fatigued\}/gi, replacement: '\]\{Утомление\}' },
        { pattern: /Enfeebl[a-z]* ([0-9]+)/gi, replacement: 'Ослаблен $1' },
        { pattern: /Drain[a-z]* ([0-9]+)/gi, replacement: 'Истощен $1' },
        { pattern: /Doom[a-z]* ([0-9]+)/gi, replacement: 'Обречен $1' },
        { pattern: /Clums[a-z]* ([0-9]+)/gi, replacement: 'Неуклюж $1' },
        { pattern: /Stupef[a-z]* ([0-9]+)/gi, replacement: 'Одурманен $1' },
        { pattern: /Sicken[a-z]* ([0-9]+)/gi, replacement: 'Тошнота $1' },
        { pattern: /Slow[a-z]* ([0-9]+)/gi, replacement: 'Замедлен $1' },
        { pattern: /Frighten[a-z]* ([0-9]+)/gi, replacement: 'Напуган $1' },
        { pattern: /\{Prone\}/gi, replacement: '\{Ничком\}' },



        { pattern: /once per round/gi, replacement: '1/Раунд' },
        { pattern: / and /gi, replacement: ' и ' },
        { pattern: / or /gi, replacement: ' или ' },
        { pattern: /\+([0-9]) (status bonus)/gi, replacement: 'Бонус Состояния +$1' },
        { pattern: /\-([0-9]) (status penalty)/gi, replacement: 'Штраф Состояния -$1' },
        { pattern: /\+([0-9]) (item bonus)/gi, replacement: 'Бонус Предмета +$1' },
        { pattern: /\-([0-9]) (item penalty)/gi, replacement: 'Штраф Предмета -$1' },
        { pattern: /\+([0-9]) (circumstance bonus)/gi, replacement: 'Бонус Обстоятельства +$1' },
        { pattern: /\-([0-9]) (circumstance penalty)/gi, replacement: 'Штраф Обстоятельства -$1' },
        { pattern: /\+([0-9]+)-foot (status bonus)/gi, replacement: 'Бонус Состояния +$1ФТ' },
        { pattern: /\-([0-9]+)-foot (status penalty)/gi, replacement: 'Штраф Состояния -$1ФТ' },
        { pattern: /\+([0-9]+)-foot (item bonus)/gi, replacement: 'Бонус Предмета +$1ФТ' },
        { pattern: /\-([0-9]+)-foot (item penalty)/gi, replacement: 'Штраф Предмета -$1ФТ' },
        { pattern: /\+([0-9]+)-foot (circumstance bonus)/gi, replacement: 'Бонус Обстоятельства +$1ФТ' },
        { pattern: /\-([0-9]+)-foot (circumstance penalty)/gi, replacement: 'Штраф Обстоятельства -$1ФТ' },
        { pattern: /([0-9]+)([a-z]*)-rank/gi, replacement: 'Ранг $1' },



        { pattern: /Stage ([0-9]+)\<\/strong\>/gi, replacement: 'Стадия $1:\<\/strong\>' },
        { pattern: /as stage ([0-9]+)/gi, replacement: 'Как Стадия $1' },
        { pattern: /(?<!for )([0-9]) (rounds)/gi, replacement: '$1 Раундов' },
        { pattern: /(?<!for )([0-9]) (round)/gi, replacement: '$1 Раунд' },
        { pattern: /for ([0-9]) (rounds)/gi, replacement: 'на $1 Раундов' },
        { pattern: /for ([0-9]) (round)/gi, replacement: 'на $1 Раунд' },
        { pattern: /for ([0-9]+) (hours)/gi, replacement: 'на $1 Часа' },
        { pattern: /for ([0-9]+) (hour)/gi, replacement: 'на $1 Час' },
        { pattern: /for ([0-9]+) (minutes)/gi, replacement: 'на $1 Минут' },
        { pattern: /for ([0-9]+) (minute)/gi, replacement: 'на $1 Минуту' },
        { pattern: /(?<!for )([0-9]+) (minutes)/gi, replacement: '$1 Минут' },
        { pattern: /(?<!for )([0-9]+) (minute)/gi, replacement: '$1 Минуту' },
        { pattern: /(?<!for )([0-9]+) (hours)/gi, replacement: '$1 Часа' },
        { pattern: /(?<!for )([0-9]+) (hour)/gi, replacement: '$1 Час' },
        { pattern: /([0-9]+) (days)/gi, replacement: '$1 Дней' },
        { pattern: /([0-9]+) (day)/gi, replacement: '$1 День' },
        { pattern: /([0-9]+) (weeks)/gi, replacement: '$1 Недель' },
        { pattern: /([0-9]+) (week)/gi, replacement: '$1 Неделя' },
        { pattern: /\]\{([0-9]+)d([0-9]+) rounds\}/gi, replacement: '\]\{$1d$2 Раундов\}' },


        { pattern: /`Противодейств[а-я]*`/gi, replacement: '@UUID[Compendium.pf2e.journals.JournalEntry.S55aqwWIzpQRFhcq.JournalEntryPage.mmfWcV3Iyql5nzTo]' },
        { pattern: /Вспомн[а-я]* Информ[а-я]*/gi, replacement: '@UUID[Compendium.pf2e.actionspf2e.1OagaWtBpVXExToo]{Вспом.Информ.}' },

        
        { pattern: /<section class=\"statblock\"><h4>/gi, replacement: '<section class=\"БлокСтат\"><h4>' },
        { pattern: /<section class=\"statblock\"><img/gi, replacement: '<section class=\"ПРАВ\"><img' },
        // Добавьте другие паттерны здесь
      ];
  
      // Функция для автозамены текста
    function performAutoReplace() {
        const editorElement = document.querySelector('.editor.prosemirror .ProseMirror');
        if (!editorElement) {
          console.warn('Editor not found.');
          return;
        }
  
        // Получаем текущее содержимое редактора как текст
        let editorContent = editorElement.innerHTML;
  
        // Выполняем замену по паттернам
        patterns.forEach(({ pattern, replacement }) => {
          editorContent = editorContent.replace(pattern, replacement);
        });
  
        // Обновляем содержимое редактора
        editorElement.innerHTML = editorContent;
  
        console.log('Text auto-replacement performed.');
      }
  
      // Добавляем действие на клик
      tsButton.find('button').click(() => {
        performAutoReplace();
      });
  
      // Используем MutationObserver для отслеживания изменений в DOM
      const observer = new MutationObserver((mutationsList) => {
        for (const mutation of mutationsList) {
          if (mutation.type === 'childList') {
            const menu = $(mutation.target).find('.editor-menu');
            if (menu.length && !menu.find('.ts-button').length) { // Проверяем, добавлена ли кнопка
              // Вставляем кнопку в меню
              menu.append(tsButton);
              console.log("TS Button added successfully!");
            }
          }
        }
      });
  
      // Начинаем наблюдение за изменениями в body
      observer.observe(document.body, { childList: true, subtree: true });
    }
  }
  
  // Хук на рендеринг страницы журнала
  Hooks.on("renderJournalSheet", (app, html, data) => {
    TSButton.addTSButton();
  });